### ISSUE TITLE
Use Amazon wish list URLs instead of dummy items

### ISSUE THREAD

**Issue by ptressel** [SeattleGiveCamp/SGC2017_QAFoodBank#26]
Stephanie has put together a separate wish list on Amazon for each major item.  She would like us to use the wish list URLs in place of the queries we used for the demo.  She does not need any secondary sources -- just one per item.  (It is ok to leave in the functionality for multiple sources, in case another food bank does want that.)

Does anyone have the wish list URLs?

**Comment by SuccessSureshP** [comment]
This has been completed. Added all the items from Amazon Wishlist (https://www.amazon.com/hz/wishlist/ls/86A1X46UWQPH/ref=cm_go_nav_hz) into the database.
